const STRIPE_SECRET_KEY: string = process.env.STRIPE_SECRET_KEY || '';
const STRIPE_PUBLIC_KEY: string = process.env.STRIPE_PUBLIC_KEY || '';
const STRIPE_API_VERSION: string = process.env.STRIPE_API_VERSION || '';
const API_BASE: string = process.env.API_BASE || process.env.NEXT_PUBLIC_API_BASE || '';
// Firebase
const FIREBASE_API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY || '';
const FIREBASE_AUTH_DOMAIN= process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || '';
const FIREBASE_PROJECT_ID= process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || '';
const FIREBASE_STORAGE_BUCKET= process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || '';
const FIREBASE_MESSAGING_SENDER_ID= process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '';
const FIREBASE_APP_ID= process.env.NEXT_PUBLIC_FIREBASE_APP_ID || '';
const FIREBASE_MEASUREMENT_ID= process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID || '';

const env = {
  STRIPE_API_VERSION,
  STRIPE_SECRET_KEY,
  STRIPE_PUBLIC_KEY,
  API_BASE,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID,
}
export default env;

export enum API_METHODS {
  POST= 'POST',
}
